# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main", "production" ]
  pull_request:
    branches: [ "main", "production" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest

        env:
          TWILIO_ACCOUNT_SID: "y7^zo53cwo$0!4(7ife!=%$46wk=6*)g$rgivz41uncm%z@)"
          TWILIO_AUTH_TOKEN: "ljvvuctxrcyubibibyvutvu"
          TWILIO_PHONE_NUMBER: "+120255501006"
          USE_TWILIO: 0
          BASE_URL: 'https://jcxq1mw7-8000.asse.devtunnels.ms/'
          RESET_PHRASE: 'reset'
          STATE_BACKEND: 'memory' 
          DATABASE_URL: 'sqlite:///./state.db'